name: Build and test the project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build on .net core 3:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: src
        
    steps:
    - uses: actions/checkout@v2
    - name: Build and test project
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Run tests
      run: dotnet test --no-restore --verbosity normal
