name: Build and test the project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: src
        
    steps:
    - uses: actions/checkout@v2
    - name: 🔨 Use .NET Core 2.0 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.0.x'
    - name: 🔨 Use .NET Core 3.0 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.x'
    - name: 🪓 **DOTNET HACK** 🪓
      shell: pwsh
      run: |
        $version = Split-Path (Split-Path $ENV:DOTNET_ROOT -Parent) -Leaf;
        $root = Split-Path (Split-Path $ENV:DOTNET_ROOT -Parent) -Parent;
        $directories = Get-ChildItem $root | Where-Object { $_.Name -ne $version };
        foreach ($dir in $directories) {
          $from = $dir.FullName;
          $to = "$root/$version";
          Write-Host Copying from $from to $to;
          Copy-Item "$from\*" $to -Recurse -Force;
        }
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Run tests
      run: dotnet test --no-restore --verbosity normal
