name: .NET Core

on:
  pull_request:
    branches: [ master, develop ]
    paths:
      - 'src/**'

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: src

    strategy:
      matrix:
        dotnet: [ '2.2.x', '3.1.x', '5.0' ]
        
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
