name: .NET Core

on:
  pull_request:
    branches: [ master, develop ]
    paths:
      - 'src/**'

jobs:
  build:

    runs-on: windows-latest
    
    defaults:
      run:
        working-directory: src
        
    strategy:
      matrix:
        dotnet: [ '2.2.x', '3.1.x' ]
    
    name: Run on .NET ${{ matrix.dotnet }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
