name: Create Release

on:
  pull_request:
    types: [closed]
    branches: [master]
    paths:
      - 'src/**'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: src

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
        dotnet: [ '2.1.x', '2.2.x', '3.0.x', '3.1.x' ]

    name: ${{ matrix.dotnet }} on '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

  release:

    runs-on: windows-latest

    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Install Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Generate NuGet Package
        run: |
          cd Collections.Extensions.ToPyString
          dotnet pack -c Release -o out --no-restore --no-build
      - name: Push generated package to NuGet registry
        run: dotnet nuget push Collections.Extensions.ToPyString\out\*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --no-symbols true --skip-duplicate
